### ISSUE TITLE
any help :D

### ISSUE THREAD

**Issue by echb** [Polight/lego#19]
i really like web components and finally found a nice library 

i tried your example [https://lego.js.org/getting-started/](url)  but..

step 1: npm init -y
step 2: create a file bricks/hello-world.html (with your example code)
step 3: npx @polight/lego and then throw an error

```js
⚠️  Missing lego.config.js file, building with defaults.
El formato del par�metro no es correcto: "bricks".
(node:12984) UnhandledPromiseRejectionWarning: Error: Command failed: cmd /c dir /s /b ./bricks
El formato del par�metro no es correcto: "bricks".

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:15)
    at walkDir "(myPath)"
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled 
promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). 
(rejection id: 3)
(node:12984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by echb** [comment]
i just realized writing `npx @polight/lego bricks` (bricks is the file created before -->bricks/hello-world.html<--) instead of just `npx @polight/lego` do the job XD

**Comment by vinyll** [comment]
Hey @echb,

Thanks for reporting this.

`bricks` is the default folder name where you store your component and should therefore work with `npx @polight/lego`, just as you did in the first place.
I'm guessing you're using Windows, is that correct?

I don't have a Windows anywhere around but if you have the chance to debug I could eventually assist you!

Could you create a file called `lego.config.js` at the root of you project with this:
```
export default {
  sourceDir: 'bricks',
}
```

and then run `npx @polight/lego` with no extra param and see if it works?
I'm guessing Windows doesn't like paths like `./bricks` which [is the default value](https://github.com/Polight/lego/blob/master/src/compiler/config.js#L13)

**Comment by mark-russ** [comment]
It can't even find the `lego.config.js` file on my machine, also Windows.
![image](https://user-images.githubusercontent.com/1957928/142744128-104005f5-617f-41df-9521-bf96b95333ee.png)


![image](https://user-images.githubusercontent.com/1957928/142744134-a47a78b4-2ef2-40c7-b0c7-31e0e330576b.png)
