### ISSUE TITLE
Default path issues on Windows

### ISSUE THREAD

**Issue by vinyll** [Polight/lego#20]
Related to #19 

I'm supposing Windows does not support `./` paths.
However the default paths innn config are `./bricks` and `./dist` for now and may have further slash path later.

A resolution might be to replace `/` with `\` when Windows is detected.
Anyone with a little Windows experience is more than welcome to suggest :)

**Comment by mark-russ** [comment]
It can't even find the `lego.config.js` file on my machine, also Windows.
![image](https://user-images.githubusercontent.com/1957928/142744128-104005f5-617f-41df-9521-bf96b95333ee.png)


![image](https://user-images.githubusercontent.com/1957928/142744134-a47a78b4-2ef2-40c7-b0c7-31e0e330576b.png)

**Comment by vinyll** [comment]
Cool, thanks for the fix!
It may solve the fact that it can't find /lego.config.js and that's great!
However #19 is happening at a different location: the [default config](https://github.com/Polight/lego/blob/master/src/compiler/config.js#L13) refers to `./bricks` which should be `.\bricks` on Windows I believe.
We may need a function to convert paths (`fixPath(<str>) <str>` or something) to Windows so that we can use it here and there.

**Comment by TotallyInformation** [comment]
I'm still getting the same error on Windows

**Comment by vinyll** [comment]
Hey, thanks for sharing these issues!

The commmand is `npx @polight/lego -w <sourceDir> <targetDir>`.
`sourceDir` is your folder with your `.html` components
`targetDir` are your compiled `.js` components

What is happening here is that your targetdir is the same as your sourcedir and therefore when you compile it detects changes and compiles again and detects changes and…

A best practice would be to have your source files in a dedicated folder and eventually your target files in a different folder.
If you need to have both in your root folder then you could remove the `-w` so it will compile without watching and looping.

**Comment by vinyll** [comment]
> Using as npx @polight/lego . . does work. Perhaps the documentation needs updating?
> Also running npm lego as per https://lego.js.org/compile-components/ seems to do something completely different - and doesn't work either.

Indeed the documentation was not consistently updated as we wanted to simplify and you pointed out an incoherence.

We should probably document the steps as follow:
1. Install with `npm install @polight/lego`
2. run `npx lego` to compile or `npx lego -w` to watch & compile

And then stick with `npx lego <options>` all the way.

Would it make more sense to you @TotallyInformation?

**Comment by TotallyInformation** [comment]
> What is happening here is that your targetdir is the same as your sourcedir and therefore when you compile it detects changes and compiles again and detects changes and…

OK, thanks for that. Can I suggest that something is added as a note to the documentation?

**Comment by TotallyInformation** [comment]
> Would it make more sense to you

Many thanks for the rapid reply. Yes, that would indeed be better. Along with the note to not use -w with everything in 1 folder ;-)

Just a note though that `npx lego` didn't seem to work? Only `npx @polight/lego` actually worked. Also neither worked (on Windows anyway) without at least pointing it at both the source and dest folders, e.g. `npx @polight/lego` did not work, `npx @polight/lego . .` did work. That may have been though because I initially failed to make the change to package.json to make it a module type so it didn't find a default config js file.

So you may want to change the docs to indicate that `npx @polight/lego` only works if it finds a config file. otherwise `npx @polight/lego src/ dist/` or similar is needed.

**Comment by vinyll** [comment]
> Just a note though that npx lego didn't seem to work? Only npx @polight/lego actually worked

If you run `npm install @polight/lego` upon installation then you can use `npx lego` for compiling.
If for some reason that would still not be the case then we should investigate further as it works on my end.

> `npx @polight/lego` did not work, `npx @polight/lego . .` did work.

Can you output here what error you have when you say "it doesn't work"?
If you follow the [getting started](https://lego.js.org/getting-started/#hello-world) you should have a `./bricks` folder, and that matched the default `sourceDir` (see [the sourceDir config](https://github.com/Polight/lego/blob/master/src/compiler/config.js#L13)).
When compiling it defaults to `./dist` (see [the targetDir config](https://github.com/Polight/lego/blob/master/src/compiler/config.js#L16)).
Therefore just running `npx run @polight/lego -w` would do the same as running `npx run @polight/lego -w bricks dist`.
Note that if these folder names don't fit yo well you may as well override these settings in a custom settings file [as documented](https://lego.js.org/configuring-components/).

> Oh, and sorry to be a bit picky. But it would be great if you gave a bit more of an explanation of the leading environment variable. It isn't obvious that the default build results in a dependency on unpkg which may cause issues in some cases where it may not be accessible or desirable.

That's a very good point as the env variable is deprecated.
Creating a `./lego.config.js` and [overriding the `importPath`](https://github.com/Polight/lego/blob/master/src/compiler/config.js#L5).
The [documentation about configuration](https://lego.js.org/configuring-components/) mention about this file.

@TotallyInformation documenting these elements you very well pointed out would greatly improve the quality of the project.
If you feel like suggesting a PR of some part of it, I'll be very enthusiast to merge your work or collaborate along with you :)

**Comment by TotallyInformation** [comment]
> If you run npm install @polight/lego upon installation then you can use npx lego for compiling.
> If for some reason that would still not be the case then we should investigate further as it works on my end.

OK. I get that now thanks.

> Can you output here what error you have when you say "it doesn't work"?

![image](https://user-images.githubusercontent.com/1591850/159534500-2bd83622-bfa9-43f2-8ff0-90c6040eca2d.png)

![image](https://user-images.githubusercontent.com/1591850/159534596-121fad28-1058-4848-ae30-92fedbfb78d2.png)

When I moved the source file into a sub-folder called `bricks` and created a sub-folder called `dist`, then `npx @polight/lego` DOES work.

However, those folder names are not explicitly listed anywhere in the docs. So again, it would be good to get the docs a bit more explicit.

![image](https://user-images.githubusercontent.com/1591850/159535676-b0d4327c-415d-4bd5-a96f-df23a80ca475.png)

The `bricks/` part is very easily missed. A paragraph on the default folder names is all that is needed I think.

> documenting these elements you very well pointed out would greatly improve the quality of the project. If you feel like suggesting a PR of some part of it, I'll be very enthusiast to merge your work or collaborate along with you :)

I'll see if I can get some time.

**Comment by vinyll** [comment]
For the record: the first thing to check when you have an issue here is to make sure your root _package.json_ contains `"type: "module,""`
@mark-russ is that related to the issue you had if you can still figure?

@TotallyInformation I've improved the documentation at https://lego.js.org/getting-started/.
Does that make more sense to you?

**Comment by mark-russ** [comment]
@vinyll Nope. I cloned your project here:
https://github.com/Polight/lego-demo/

Brand new setup on Windows:
![image](https://user-images.githubusercontent.com/1957928/184550930-93e24a2a-fdd9-4a47-ba27-020458f0e3ba.png)

It just works. From installation to compilation.

**Comment by vinyll** [comment]
Note that if you first install Lego with `npm i @polight/lego`, you may then compile with `npx lego`.

**Comment by vinyll** [comment]
The documentation was [improved to make folders requirements clearer](https://github.com/Polight/lego/commit/e3a3ea00798bd49765289b5f270f3bff83bed6d1).
I'll close this as it may be solved.

Feel free to reopen if it still occurs
