### ISSUE TITLE
interact between components

### ISSUE THREAD

**Issue by monsterbitar** [Polight/lego#44]
After I have made some components, how do I expose functions or data from one component, to be used by a different component?

**Comment by vinyll** [comment]
That's a very intersting point.
A component is basically an HTMLElement, meaning you can access methods from that components just like you would from another HTML element.

_/bricks/x-compo.html_
```
<script>
export default class extends Lego {
  doThisAlert() {
    alert('hello')
  }
}
</script>
```

could be called from another component like so
```
<template>
  <x-compo></x-compo>
</template>

<script>
  const component = this.document.querySelector('x-compo')
  component.doThisAlert()
</script>
```

I typed this script from Github, it's untested but should be close to work.

Note that [Lego v2](https://github.com/Polight/lego/tree/v2) is coming and suggesting a [Store](https://github.com/Polight/store) that should also work with V1.

**Comment by monsterbitar** [comment]
is it enough to export named functions from the component, or does it have to be wrapped in a class for it to pick it up?

**Comment by vinyll** [comment]
In Lego V1 it should be a method of the component as [shown on the example](https://github.com/Polight/lego/issues/44#issuecomment-1586320600).
In Lego V2 it can be a method wrapped in the `setup()` or  `connected()` callbacks:

```html
function setup() {
  this.doThisAlert = () => {
    alert('hello')
  }
}
```

The syntax of v1 is also backward compatible in v2.

Does that clarify?

**Comment by monsterbitar** [comment]
yes, thank you.
