### ISSUE TITLE
Separation by file

### ISSUE THREAD

**Issue by monsterbitar** [Polight/lego#46]
Currently, a component consist of up to three different types of content (template, style, script) in the same file. this makes it more difficult for multiple developers to work on the same components, particular if components are large.

Perhaps this can be better handled by splitting the three functions into separate files, by some naming convention? perhaps like aurelia does it where they have component.html, component.css and component.js/ts

**Comment by vinyll** [comment]
I know Aurelia and Angular manage files to be splitted while React, Vue, Riot, Svelte and most other approach tend to prefer a single file.

Lego suggest the latest approach, however the developer has the full flexibility to import scripts.

Here's an example based on [Lego V2](https://github.com/Polight/lego/tree/v2):

```
<script>
  import myComponent from './mycomponent.js'
<script>

<style>
  @import "mycomponent.css";
</style>

<template>
  <h1>Hello World</h1>
</template>
```

This way you can even get super-powers and use things like `@import url("mycomponent.css") screen and (orientation: landscape);` for selecting css based on media queries or go wild with [CSS Layers](`https://developer.mozilla.org/en-US/docs/Web/CSS/@layer`) 😎

**Comment by monsterbitar** [comment]
Great, I should've thought of that! :)
